jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: false
    - continue-on-error: true
      name: Run build with Gradle Wrapper
      run: ./gradlew build -Dbuild.release=true
    - continue-on-error: true
      name: Upload artifacts to Modrinth and GitHub
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        curseforge-id: 455508
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        dependencies: sodium
        files: build/libs/!(*-@(dev|sources|all)).jar
        github-token: ${{ secrets.GITHUB_TOKEN }}
        loaders: fabric quilt
        modrinth-featured: true
        modrinth-id: YL57xq9U
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        version-resolver: latest
        version-type: release
name: Release script
on:
  repository_dispatch:
    types: trigger-ga___build-release.yml
