jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: false
    - continue-on-error: true
      name: Run build with Gradle Wrapper
      run: ./gradlew build
    - continue-on-error: true
      name: Upload built JAR (Fabric)
      uses: actions/upload-artifact@v3
      with:
        name: iris-artifacts
        path: build/libs
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___build.yml
